name: Master-Pipeline

on:
    push:
        branches:
            - master

jobs:
    test-doctest:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Run the doc tests
              run: |
                cd src/spreadsheetapi
                python -m doctest service/backends/transforms.py
    test-inmemory:
        needs: test-doctest
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pipenv
                cd src/spreadsheetapi
                pipenv install --deploy --ignore-pipfile
            - name: Run the spreadsheet API
              # NOTE: Using 0.0.0.0 as the host is not ideal here (security
              # risk, question - what firewall rules does github have setup for
              # these VMs?), but in order for the spreadsheet-api-tests
              # container to have access to this service this is the simplest
              # solution for now. If github actions supports setting network
              # mode = host for the action or if the service here is updated to
              # run as a container on the default bridge network this would be
              # more secure.
              run: |
                cd src/spreadsheetapi/service
                pipenv run uvicorn application:app --host 0.0.0.0 --port 8000 &> /dev/null &
              env:
                  BACKEND: InMemory
            - uses: ed-rw/spreadsheet-api-tests@master
              with:
                  service-base-url: http://172.17.0.1:8000
    test-sqlite:
        needs: test-doctest
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pipenv
                cd src/spreadsheetapi
                pipenv sync
            - name: Run the spreadsheet API
              # NOTE: Same issue noted above
              run: |
                cd src/spreadsheetapi/service
                mkdir .db
                pipenv run uvicorn application:app --host 0.0.0.0 --port 8000 &> /dev/null &
              env:
                  BACKEND: SQLite
            - uses: ed-rw/spreadsheet-api-tests@master
              with:
                  service-base-url: http://172.17.0.1:8000
    # Dont deploy since app is no longer running live
    # deploy-to-app-platform:
    #     # Skip Non-deploy commits
    #     if: "! startsWith(github.event.head_commit.message, 'ND:')"
    #
    #     needs: [test-inmemory, test-sqlite]
    #
    #     runs-on: ubuntu-latest
    #
    #     steps:
    #         - uses: actions/checkout@v2
    #         - name: Set up Terraform
    #           uses: hashicorp/setup-terraform@v1
    #           with:
    #               terraform_version: 0.14.7
    #               cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    #               # The wrapper hides terraform output, making it tricky to
    #               # get the value of the app_platform_id
    #               terraform_wrapper: false
    #         - name: Install doctl
    #           uses: digitalocean/action-doctl@v2
    #           with:
    #               token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    #         - name: Output App Platorm Id
    #           id: get_app_platform_id
    #           run: |
    #             cd terraform
    #             terraform init
    #             terraform validate
    #             echo "::set-output name=app_platform_id::$(terraform output app_platform_id)"
    #         - name: Initiate deployment
    #           run: doctl app create-deployment ${{steps.get_app_platform_id.outputs.app_platform_id}}
